# Window and Session indexing
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# Keybindings
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Hot reload
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Mouse
set -g mouse on

# Style
set -g status-style bg=default
set -g status-right "#S"
set -g status-left " "
setw -g window-status-current-style fg=colour39,bold
setw -g window-status-current-format "#I:#W"
